version: "3.7"

services:

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
  
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: